// Monsters and enemy attack defaults.

const DEFAULT_ATTACK = {
  type: "normal",
  parryable: true,
  blockable: true,
  dodgeable: true,
  pierces_guard: false,
  accuracy: 100,
  hits: 1,
  special_effect: null,
  warning: false,
  telegraph: "is preparing",
  element: null,
};

const EFFECT_STYLE = {
  poison: ["☠️", "poisoned"],
  burn: ["🔥", "burning"],
  bleed: ["🩸", "bleeding"],
  slow: ["❄️", "slowed"],
  weakened: ["📉", "weakened"],
  empowered: ["📈", "empowered"],
  shield: ["🔰", "shielded"],
  fortified: ["🛡️", "fortified"],
  warded: ["✨", "warded"],
};

const IDLE_LINES = [
  "is catching its breath...",
  "looks around, unsure what to do...",
  "hesitates...",
  "is just watching you...",
];

const monsters = {
  rat: {
    icon: "🐀",
    hp: 22,
    block_chance: 3,
    block_reduction: 0.4,
    basic_attack: { damage: [3, 5] },
    abilities: { "quick bite": { chance: 30, damage: [4, 7], type: "fast" } },
    chance: 90,
    drops: {
      meat: { chance: 100, min_drop: 1, max_drop: 2 },
      fur: { chance: 60, min_drop: 1, max_drop: 2 },
      fiber: { chance: 30, min_drop: 1, max_drop: 2 },
      "rat fang": { chance: 15, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 0,
    dodge_chance: 20,
    parry_rate: 0,
    dodge_rate: 60,
  },
  slime: {
    icon: "🟢",
    hp: 30,
    block_chance: 10,
    block_reduction: 0.5,
    basic_attack: { damage: [3, 6] },
    abilities: {
      "acid splash": {
        chance: 25,
        damage: [6, 10],
        type: "fast",
        special_effect: { type: "poison", chance: 35, damage: 2, turns: 2 },
      },
    },
    chance: 100,
    drops: {
      wood: { chance: 100, min_drop: 5, max_drop: 10 },
      fiber: { chance: 35, min_drop: 1, max_drop: 3 },
      crystal: { chance: 8, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 0,
    dodge_chance: 10,
    parry_rate: 0,
    dodge_rate: 40,
  },
  goblin: {
    icon: "👺",
    hp: 35,
    block_chance: 15,
    block_reduction: 0.5,
    basic_attack: { damage: [4, 8] },
    abilities: {
      "dagger stab": { chance: 30, damage: [6, 10], type: "fast" },
      "thrown rock": { chance: 20, stun: 25, stun_turns: 1, damage: [5, 9], parryable: false, telegraph: "hurls" },
      "dirty trick": {
        chance: 10, stun: 30, stun_turns: 1,
        damage: [3, 6],
        accuracy: 90,
        special_effect: { type: "bleed", chance: 60, damage: 2, turns: 3 },
      },
    },
    chance: 90,
    drops: {
      coin: { chance: 100, min_drop: 5, max_drop: 15 },
      leather: { chance: 45, min_drop: 1, max_drop: 3 },
      iron: { chance: 25, min_drop: 1, max_drop: 2 },
      coal: { chance: 15, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 5,
    dodge_chance: 15,
    parry_rate: 40,
    dodge_rate: 55,
  },
  wolf: {
    icon: "🐺",
    hp: 40,
    block_chance: 5,
    block_reduction: 0.4,
    basic_attack: { damage: [6, 10] },
    abilities: {
      "savage bite": {
        chance: 30,
        damage: [7, 11],
        type: "fast",
        special_effect: { type: "bleed", chance: 45, damage: 3, turns: 3 },
      },
      pounce: {
        chance: 20, stun: 30, stun_turns: 2,
        damage: [11, 16],
        type: "heavy",
        parryable: false,
        telegraph: "coils up to unleash",
      },
      howl: { chance: 10, stun: 20, stun_turns: 2, heal: [5, 10], telegraph: "raises its head and uses" },
    },
    chance: 100,
    drops: {
      leather: { chance: 80, min_drop: 1, max_drop: 3 },
      fang: { chance: 40, min_drop: 1, max_drop: 2 },
      bone: { chance: 15, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 0,
    dodge_chance: 20,
    parry_rate: 0,
    dodge_rate: 65,
  },
  "wild boar": {
    icon: "🐗",
    hp: 55,
    block_chance: 12,
    block_reduction: 0.5,
    basic_attack: { damage: [7, 11] },
    abilities: {
      charge: {
        chance: 25, stun: 40, stun_turns: 2,
        damage: [12, 18],
        type: "heavy",
        telegraph: "lowers its head and charges",
      },
    },
    chance: 75,
    drops: {
      meat: { chance: 100, min_drop: 2, max_drop: 4 },
      leather: { chance: 65, min_drop: 1, max_drop: 3 },
    },
    parry_chance: 5,
    dodge_chance: 5,
    parry_rate: 35,
    dodge_rate: 30,
  },
  zombie: {
    icon: "🧟",
    hp: 50,
    block_chance: 15,
    block_reduction: 0.5,
    basic_attack: { damage: [5, 9] },
    abilities: {
      "infected bite": {
        chance: 30,
        damage: [8, 12],
        type: "fast",
        special_effect: { type: "poison", chance: 50, damage: 3, turns: 3 },
      },
      "rotten lunge": { chance: 20, damage: [9, 13], type: "slow", telegraph: "slowly winds up" },
      grab: {
        chance: 12, stun: 30, stun_turns: 2,
        damage: [6, 10],
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "lunges forward with",
      },
      regenerate: { chance: 15, heal: [6, 12] },
    },
    chance: 75,
    drops: {
      iron: { chance: 60, min_drop: 1, max_drop: 4 },
      coin: { chance: 100, min_drop: 5, max_drop: 20 },
      bone: { chance: 50, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 5,
    dodge_chance: 0,
    parry_rate: 30,
    dodge_rate: 0,
  },
  "giant spider": {
    icon: "🕷️",
    hp: 45,
    block_chance: 5,
    block_reduction: 0.4,
    basic_attack: { damage: [5, 9] },
    abilities: {
      "venom bite": {
        chance: 35,
        damage: [6, 10],
        type: "fast",
        special_effect: { type: "poison", chance: 65, damage: 4, turns: 3 },
      },
      "web spit": {
        chance: 20,
        damage: [4, 7],
        parryable: false,
        telegraph: "spits",
        special_effect: { type: "poison", chance: 25, damage: 2, turns: 2 },
      },
      "web trap": {
        chance: 10, stun: 35, stun_turns: 2,
        damage: [2, 5],
        parryable: false,
        blockable: false,
        special_effect: { type: "bleed", chance: 50, damage: 2, turns: 2 },
      },
    },
    chance: 85,
    drops: {
      silk: { chance: 75, min_drop: 1, max_drop: 3 },
      fang: { chance: 40, min_drop: 1, max_drop: 2 },
      coin: { chance: 100, min_drop: 4, max_drop: 14 },
    },
    parry_chance: 0,
    dodge_chance: 15,
    parry_rate: 0,
    dodge_rate: 60,
  },
  skeleton: {
    icon: "💀",
    hp: 55,
    block_chance: 20,
    block_reduction: 0.5,
    basic_attack: { damage: [7, 11] },
    abilities: {
      "spinning bone": {
        chance: 25,
        damage: [8, 12],
        type: "slow",
        parryable: false,
        telegraph: "hurls a",
      },
      "shield bash": {
        chance: 20, stun: 40, stun_turns: 2,
        damage: [10, 14],
        type: "heavy",
        pierces_guard: true,
        blockable: false,
        warning: true,
        telegraph: "braces its shield for",
      },
      reassemble: { chance: 10, heal: [8, 14] },
    },
    chance: 80,
    drops: {
      bone: { chance: 85, min_drop: 1, max_drop: 3 },
      iron: { chance: 40, min_drop: 1, max_drop: 3 },
      "silver ore": { chance: 12, min_drop: 1, max_drop: 2 },
      coin: { chance: 100, min_drop: 8, max_drop: 25 },
    },
    parry_chance: 15,
    dodge_chance: 5,
    parry_rate: 55,
    dodge_rate: 35,
  },
  "giant crab": {
    icon: "🦀",
    hp: 65,
    block_chance: 40,
    block_reduction: 0.7,
    basic_attack: { damage: [6, 10], type: "slow" },
    abilities: {
      "pincer snap": { chance: 30, damage: [9, 14], type: "heavy" },
      "bubble spray": { chance: 20, damage: [4, 8], parryable: false, telegraph: "sprays" },
      "harden shell": { chance: 15, heal: [6, 10] },
    },
    chance: 70,
    drops: {
      shell: { chance: 85, min_drop: 1, max_drop: 3 },
      coin: { chance: 100, min_drop: 8, max_drop: 20 },
      crystal: { chance: 5, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 10,
    dodge_chance: 0,
    parry_rate: 45,
    dodge_rate: 0,
  },
  harpy: {
    icon: "🦅",
    hp: 45,
    block_chance: 5,
    block_reduction: 0.3,
    basic_attack: { damage: [6, 10], type: "fast" },
    abilities: {
      "dive bomb": {
        chance: 30,
        damage: [10, 15],
        type: "heavy",
        parryable: false,
        warning: true,
        telegraph: "screeches and dives with",
      },
      "talon rake": {
        chance: 30,
        damage: [6, 10],
        type: "fast",
        special_effect: { type: "bleed", chance: 40, damage: 2, turns: 3 },
      },
      "piercing screech": {
        chance: 15, stun: 30, stun_turns: 2,
        damage: [3, 6],
        parryable: false,
        blockable: false,
        telegraph: "lets out a",
      },
    },
    chance: 80,
    drops: {
      feather: { chance: 90, min_drop: 1, max_drop: 4 },
      coin: { chance: 100, min_drop: 6, max_drop: 18 },
      fang: { chance: 10, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 0,
    dodge_chance: 25,
    parry_rate: 0,
    dodge_rate: 70,
  },
  "armored goblin": {
    icon: "👺",
    hp: 65,
    block_chance: 25,
    block_reduction: 0.55,
    basic_attack: { damage: [7, 11] },
    abilities: {
      "shield bash": { chance: 20, stun: 40, stun_turns: 2, damage: [6, 9], type: "heavy" },
      "guard break": { chance: 15, stun: 35, stun_turns: 2, damage: [9, 13] },
    },
    chance: 55,
    drops: {
      iron: { chance: 60, min_drop: 1, max_drop: 3 },
      leather: { chance: 70, min_drop: 2, max_drop: 4 },
      "goblin blade": { chance: 12, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 15,
    dodge_chance: 8,
    parry_rate: 50,
    dodge_rate: 40,
  },
  orc: {
    icon: "👹",
    hp: 75,
    block_chance: 25,
    block_reduction: 0.5,
    basic_attack: { damage: [9, 14] },
    abilities: {
      cleave: { chance: 25, damage: [14, 20], type: "heavy" },
      "reckless swing": { chance: 20, damage: [11, 16], type: "fast", accuracy: 75 },
      "crushing blow": {
        chance: 12, stun: 40, stun_turns: 3,
        damage: [16, 22],
        type: "slow",
        parryable: false,
        blockable: false,
        warning: true,
        telegraph: "raises its club to deliver",
      },
      "battle roar": { chance: 8, stun: 25, stun_turns: 2, heal: [10, 18] },
    },
    chance: 70,
    drops: {
      iron: { chance: 75, min_drop: 2, max_drop: 6 },
      leather: { chance: 60, min_drop: 1, max_drop: 3 },
      coin: { chance: 100, min_drop: 15, max_drop: 45 },
      coal: { chance: 30, min_drop: 1, max_drop: 3 },
      "orc tusk": { chance: 15, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 15,
    dodge_chance: 5,
    parry_rate: 50,
    dodge_rate: 20,
  },
  bandit: {
    icon: "🥷",
    hp: 60,
    block_chance: 15,
    block_reduction: 0.45,
    basic_attack: { damage: [7, 12], type: "fast" },
    abilities: {
      "poisoned dagger": {
        chance: 25,
        damage: [7, 11],
        type: "fast",
        special_effect: { type: "poison", chance: 45, damage: 3, turns: 3 },
      },
      "throwing knife": {
        chance: 20,
        damage: [6, 10],
        parryable: false,
        accuracy: 90,
        telegraph: "draws and throws",
      },
      "smoke bomb": { chance: 10, stun: 30, stun_turns: 2, heal: [8, 15] },
    },
    chance: 70,
    drops: {
      coin: { chance: 100, min_drop: 15, max_drop: 35 },
      iron: { chance: 35, min_drop: 1, max_drop: 3 },
      silk: { chance: 25, min_drop: 1, max_drop: 2 },
      fang: { chance: 15, min_drop: 1, max_drop: 1 },
      "silver ore": { chance: 12, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 15,
    dodge_chance: 20,
    parry_rate: 55,
    dodge_rate: 60,
  },
  "bandit captain": {
    icon: "🗡️",
    hp: 90,
    block_chance: 18,
    block_reduction: 0.5,
    basic_attack: { damage: [10, 15] },
    abilities: {
      "commanding strike": { chance: 25, damage: [13, 19] },
      "quick slash": { chance: 20, damage: [7, 11], type: "fast" },
    },
    chance: 40,
    drops: {
      coin: { chance: 100, min_drop: 30, max_drop: 70 },
      iron: { chance: 70, min_drop: 2, max_drop: 5 },
      leather: { chance: 70, min_drop: 2, max_drop: 4 },
      "gold ore": { chance: 20, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 20,
    dodge_chance: 18,
    parry_rate: 55,
    dodge_rate: 55,
  },
  witch: {
    icon: "🧙",
    hp: 70,
    block_chance: 10,
    block_reduction: 0.4,
    basic_attack: { damage: [6, 10], type: "slow" },
    abilities: {
      "shadow bolt": { chance: 30, damage: [10, 16], type: "fast", parryable: false },
      curse: {
        chance: 18,
        damage: [5, 9],
        type: "slow",
        special_effect: { type: "poison", chance: 80, damage: 4, turns: 4 },
      },
      "life drain": { chance: 15, damage: [7, 12], heal: [7, 12], type: "normal" },
      "dark ritual": { chance: 8, heal: [15, 25] },
    },
    chance: 45,
    drops: {
      silk: { chance: 80, min_drop: 2, max_drop: 5 },
      crystal: { chance: 45, min_drop: 1, max_drop: 2 },
      coin: { chance: 100, min_drop: 20, max_drop: 50 },
    },
    parry_chance: 0,
    dodge_chance: 20,
    parry_rate: 0,
    dodge_rate: 55,
  },
  "fire elemental": {
    icon: "☄️",
    hp: 85,
    block_chance: 10,
    block_reduction: 0.4,
    basic_attack: { damage: [8, 13] },
    abilities: {
      "flame lash": {
        chance: 30,
        damage: [9, 14],
        type: "fast",
        special_effect: { type: "burn", chance: 40, damage: 3, turns: 3 },
        element: "fire",
      },
      fireball: {
        chance: 25,
        damage: [13, 19],
        type: "heavy",
        parryable: false,
        warning: true,
        telegraph: "gathers a blazing sphere for",
        special_effect: { type: "burn", chance: 60, damage: 4, turns: 3 },
        element: "fire",
      },
      "ember burst": {
        chance: 10,
        damage: [8, 12],
        pierces_guard: true,
        blockable: false,
        telegraph: "erupts with",
        element: "fire",
      },
    },
    chance: 50,
    drops: {
      "ember core": { chance: 60, min_drop: 1, max_drop: 2 },
      coal: { chance: 70, min_drop: 1, max_drop: 3 },
      crystal: { chance: 25, min_drop: 1, max_drop: 2 },
      coin: { chance: 100, min_drop: 20, max_drop: 45 },
    },
    parry_chance: 0,
    dodge_chance: 15,
    parry_rate: 0,
    dodge_rate: 50,
  },
  werewolf: {
    icon: "🌕",
    hp: 90,
    block_chance: 10,
    block_reduction: 0.5,
    basic_attack: { damage: [10, 15], type: "fast" },
    abilities: {
      "rending claws": {
        chance: 30,
        damage: [11, 16],
        type: "fast",
        special_effect: { type: "bleed", chance: 60, damage: 4, turns: 3 },
      },
      "lunging bite": {
        chance: 20,
        damage: [14, 20],
        type: "heavy",
        parryable: false,
        telegraph: "bares its fangs and lunges with",
      },
      frenzy: { chance: 15, damage: [8, 14], type: "fast", accuracy: 80 },
      "moonlit howl": { chance: 10, stun: 25, stun_turns: 2, heal: [10, 18], telegraph: "howls at the moon and uses" },
    },
    chance: 40,
    drops: {
      leather: { chance: 90, min_drop: 2, max_drop: 4 },
      fang: { chance: 80, min_drop: 1, max_drop: 3 },
      bone: { chance: 40, min_drop: 1, max_drop: 2 },
      coin: { chance: 100, min_drop: 25, max_drop: 55 },
    },
    parry_chance: 10,
    dodge_chance: 15,
    parry_rate: 50,
    dodge_rate: 55,
  },
  "dire wolf": {
    icon: "🐺",
    hp: 70,
    block_chance: 4,
    block_reduction: 0.4,
    basic_attack: { damage: [9, 14] },
    abilities: {
      "double bite": { chance: 25, damage: [6, 10], hits: 2, type: "fast" },
      "pack howl": { chance: 10, stun: 25, stun_turns: 2, heal: [8, 15] },
    },
    chance: 60,
    drops: {
      leather: { chance: 90, min_drop: 2, max_drop: 4 },
      fang: { chance: 65, min_drop: 1, max_drop: 3 },
      "dire fang": { chance: 15, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 0,
    dodge_chance: 25,
    parry_rate: 0,
    dodge_rate: 70,
  },
  troll: {
    icon: "👺",
    hp: 120,
    block_chance: 30,
    block_reduction: 0.6,
    basic_attack: { damage: [11, 18], type: "slow" },
    abilities: {
      "club smash": {
        chance: 25, stun: 40, stun_turns: 3,
        damage: [18, 27],
        type: "heavy",
        warning: true,
        telegraph: "raises a huge club to",
      },
      "ground slam": {
        chance: 20, stun: 35, stun_turns: 2,
        damage: [12, 20],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "stomps the ground before",
      },
      "troll regeneration": { chance: 20, heal: [15, 25] },
    },
    chance: 45,
    drops: {
      iron: { chance: 90, min_drop: 3, max_drop: 8 },
      leather: { chance: 75, min_drop: 2, max_drop: 5 },
      coin: { chance: 100, min_drop: 20, max_drop: 60 },
      crystal: { chance: 20, min_drop: 1, max_drop: 1 },
      "gold ore": { chance: 15, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 5,
    dodge_chance: 0,
    parry_rate: 35,
    dodge_rate: 0,
  },
  "ice golem": {
    icon: "🧊",
    hp: 110,
    block_chance: 35,
    block_reduction: 0.65,
    basic_attack: { damage: [9, 15], type: "slow" },
    abilities: {
      "frost punch": { chance: 25, damage: [14, 21], type: "heavy", element: "frost" },
      "ice shards": {
        chance: 25,
        damage: [7, 13],
        type: "fast",
        parryable: false,
        accuracy: 90,
        element: "frost",
      },
      "freezing blast": {
        chance: 12, stun: 30, stun_turns: 2,
        damage: [12, 18],
        type: "slow",
        pierces_guard: true,
        blockable: false,
        warning: true,
        telegraph: "gathers frost before unleashing",
        special_effect: { type: "burn", chance: 35, damage: 3, turns: 3 },
        element: "frost",
      },
    },
    chance: 35,
    drops: {
      iron: { chance: 80, min_drop: 2, max_drop: 6 },
      crystal: { chance: 75, min_drop: 1, max_drop: 3 },
      "frost crystal": { chance: 35, min_drop: 1, max_drop: 2 },
      scale: { chance: 10, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 10,
    dodge_chance: 0,
    parry_rate: 40,
    dodge_rate: 0,
  },
  vampire: {
    icon: "🧛",
    hp: 95,
    block_chance: 15,
    block_reduction: 0.5,
    basic_attack: { damage: [9, 15], type: "fast" },
    abilities: {
      "blood bite": {
        chance: 30,
        damage: [10, 17],
        type: "fast",
        special_effect: { type: "bleed", chance: 55, damage: 4, turns: 3 },
      },
      "bat swarm": { chance: 20, damage: [7, 13], parryable: false, dodgeable: true },
      "drain life": { chance: 20, damage: [8, 14], heal: [8, 14] },
    },
    chance: 30,
    drops: {
      fang: { chance: 100, min_drop: 2, max_drop: 5 },
      silk: { chance: 65, min_drop: 1, max_drop: 3 },
      crystal: { chance: 30, min_drop: 1, max_drop: 2 },
      coin: { chance: 100, min_drop: 30, max_drop: 70 },
    },
    parry_chance: 15,
    dodge_chance: 20,
    parry_rate: 60,
    dodge_rate: 65,
  },
  ogre: {
    icon: "👹",
    hp: 150,
    block_chance: 25,
    block_reduction: 0.6,
    basic_attack: { damage: [16, 24] },
    abilities: {
      "club smash": {
        chance: 25, stun: 40, stun_turns: 3,
        damage: [24, 34],
        type: "heavy",
        telegraph: "raises its club high",
      },
      roar: { chance: 10, stun: 25, stun_turns: 2, heal: [10, 20] },
    },
    chance: 30,
    drops: {
      stone: { chance: 100, min_drop: 4, max_drop: 8 },
      iron: { chance: 60, min_drop: 2, max_drop: 5 },
      "ogre hide": { chance: 35, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 8,
    dodge_chance: 0,
    parry_rate: 40,
    dodge_rate: 0,
  },
  berserker: {
    icon: "🪓",
    hp: 125,
    block_chance: 8,
    block_reduction: 0.45,
    basic_attack: { damage: [14, 22] },
    abilities: {
      frenzy: { chance: 25, damage: [10, 16], hits: 2, type: "fast" },
      "reckless swing": { chance: 20, damage: [25, 36], type: "heavy" },
    },
    chance: 28,
    drops: {
      steel: { chance: 40, min_drop: 1, max_drop: 3 },
      iron: { chance: 80, min_drop: 2, max_drop: 5 },
      "berserker hide": { chance: 25, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 5,
    dodge_chance: 10,
    parry_rate: 35,
    dodge_rate: 45,
  },
  wraith: {
    icon: "👻",
    hp: 105,
    block_chance: 0,
    block_reduction: 0.5,
    basic_attack: { damage: [11, 17] },
    abilities: {
      "soul touch": {
        chance: 30,
        damage: [13, 20],
        type: "fast",
        special_effect: { type: "bleed", chance: 35, damage: 3, turns: 3 },
      },
      phase: { chance: 10, heal: [12, 22] },
    },
    chance: 25,
    drops: {
      "soul shard": { chance: 65, min_drop: 1, max_drop: 2 },
      crystal: { chance: 50, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 5,
    dodge_chance: 30,
    parry_rate: 30,
    dodge_rate: 70,
  },
  lich: {
    icon: "👻",
    hp: 150,
    block_chance: 20,
    block_reduction: 0.5,
    basic_attack: { damage: [12, 18], type: "slow" },
    abilities: {
      "soul bolt": { chance: 30, damage: [14, 20], type: "fast", parryable: false },
      "death grip": {
        chance: 15, stun: 35, stun_turns: 2,
        damage: [10, 16],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "reaches out with",
      },
      "plague cloud": {
        chance: 20,
        damage: [6, 10],
        blockable: false,
        telegraph: "conjures a",
        special_effect: { type: "poison", chance: 80, damage: 5, turns: 4 },
      },
      "drain essence": { chance: 15, damage: [10, 16], heal: [10, 16] },
      "soul harvest": { chance: 10, heal: [15, 25] },
    },
    chance: 25,
    drops: {
      "soul shard": { chance: 70, min_drop: 1, max_drop: 2 },
      crystal: { chance: 80, min_drop: 1, max_drop: 3 },
      bone: { chance: 100, min_drop: 2, max_drop: 5 },
      coin: { chance: 100, min_drop: 60, max_drop: 140 },
      silk: { chance: 40, min_drop: 1, max_drop: 3 },
    },
    parry_chance: 10,
    dodge_chance: 10,
    parry_rate: 50,
    dodge_rate: 40,
  },
  "stone golem": {
    icon: "🗿",
    hp: 220,
    block_chance: 35,
    block_reduction: 0.7,
    basic_attack: { damage: [18, 27] },
    abilities: {
      "stone fist": { chance: 25, damage: [28, 40], type: "heavy" },
      "ground shock": { chance: 15, damage: [12, 18], parryable: false },
    },
    chance: 20,
    drops: {
      stone: { chance: 100, min_drop: 8, max_drop: 15 },
      crystal: { chance: 75, min_drop: 1, max_drop: 3 },
      "ancient crystal": { chance: 10, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 15,
    dodge_chance: 0,
    parry_rate: 50,
    dodge_rate: 0,
  },
  dragon: {
    icon: "🐉",
    hp: 100,
    block_chance: 25,
    block_reduction: 0.6,
    basic_attack: { damage: [10, 16] },
    abilities: {
      "fire breath": {
        chance: 30, stun: 30, stun_turns: 2,
        damage: [18, 26],
        type: "heavy",
        parryable: false,
        blockable: false,
        dodgeable: true,
        pierces_guard: true,
        warning: true,
        telegraph: "begins charging",
        special_effect: { type: "burn", chance: 50, damage: 4, turns: 2 },
        element: "fire",
      },
      "tail swipe": { chance: 25, stun: 35, stun_turns: 2, damage: [12, 18], type: "heavy" },
      earthquake: {
        chance: 10, stun: 40, stun_turns: 3,
        damage: [10, 16],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "is about to unleash",
      },
      "dragon roar": { chance: 8, stun: 25, stun_turns: 2, heal: [12, 20] },
    },
    chance: 50,
    drops: {
      iron: { chance: 100, min_drop: 5, max_drop: 15 },
      coin: { chance: 100, min_drop: 50, max_drop: 150 },
      scale: { chance: 70, min_drop: 1, max_drop: 3 },
      crystal: { chance: 40, min_drop: 1, max_drop: 2 },
      "dragon heart": { chance: 6, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 10,
    dodge_chance: 10,
    parry_rate: 50,
    dodge_rate: 40,
  },
  "ancient dragon": {
    icon: "🐲",
    hp: 180,
    block_chance: 30,
    block_reduction: 0.65,
    basic_attack: { damage: [14, 22], type: "heavy" },
    abilities: {
      inferno: {
        chance: 30, stun: 30, stun_turns: 2,
        damage: [25, 35],
        type: "heavy",
        parryable: false,
        blockable: false,
        dodgeable: true,
        pierces_guard: true,
        warning: true,
        telegraph: "fills the air with fire before",
        special_effect: { type: "burn", chance: 75, damage: 6, turns: 3 },
        element: "fire",
      },
      "wing storm": { chance: 20, damage: [15, 24], type: "fast", accuracy: 85 },
      "dragon claw": {
        chance: 25,
        damage: [18, 27],
        type: "normal",
        special_effect: { type: "bleed", chance: 50, damage: 5, turns: 3 },
      },
      "ancient regeneration": { chance: 15, heal: [20, 35] },
      cataclysm: {
        chance: 8, stun: 40, stun_turns: 3,
        damage: [20, 30],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "begins summoning a devastating",
      },
    },
    chance: 12,
    drops: {
      scale: { chance: 100, min_drop: 2, max_drop: 5 },
      crystal: { chance: 100, min_drop: 2, max_drop: 5 },
      iron: { chance: 100, min_drop: 10, max_drop: 25 },
      coin: { chance: 100, min_drop: 100, max_drop: 300 },
      silk: { chance: 60, min_drop: 2, max_drop: 5 },
      "dragon heart": { chance: 25, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 12,
    dodge_chance: 8,
    parry_rate: 55,
    dodge_rate: 40,
  },
  wyvern: {
    icon: "🐲",
    hp: 260,
    block_chance: 15,
    block_reduction: 0.55,
    basic_attack: { damage: [20, 30] },
    abilities: {
      "fire breath": {
        chance: 25, stun: 30, stun_turns: 2,
        damage: [25, 38],
        parryable: false,
        dodgeable: true,
        warning: true,
        telegraph: "inhales deeply before releasing",
        element: "fire",
      },
      "wing strike": { chance: 20, damage: [15, 23], type: "fast" },
    },
    chance: 15,
    drops: {
      "dragon scale": { chance: 100, min_drop: 2, max_drop: 5 },
      "dragon bone": { chance: 70, min_drop: 1, max_drop: 3 },
      crystal: { chance: 40, min_drop: 1, max_drop: 2 },
      "dragon heart": { chance: 6, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 12,
    dodge_chance: 12,
    parry_rate: 50,
    dodge_rate: 50,
  },
  demon: {
    icon: "😈",
    hp: 300,
    block_chance: 20,
    block_reduction: 0.55,
    basic_attack: { damage: [22, 33] },
    abilities: {
      hellfire: {
        chance: 25,
        damage: [25, 40],
        parryable: false,
        warning: true,
        telegraph: "summons dark flames",
        element: "fire",
      },
      "life drain": { chance: 18, damage: [15, 25], heal: [12, 22] },
      curse: {
        chance: 12,
        damage: [10, 16],
        special_effect: { type: "poison", chance: 80, damage: 5, turns: 4 },
      },
    },
    chance: 10,
    drops: {
      "demon horn": { chance: 100, min_drop: 1, max_drop: 3 },
      obsidian: { chance: 80, min_drop: 1, max_drop: 4 },
      "demon core": { chance: 20, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 12,
    dodge_chance: 12,
    parry_rate: 50,
    dodge_rate: 45,
  },
  "frost giant": {
    icon: "🧊",
    hp: 360,
    block_chance: 30,
    block_reduction: 0.6,
    basic_attack: { damage: [24, 36] },
    abilities: {
      "ice smash": { chance: 25, stun: 35, stun_turns: 3, damage: [30, 45], type: "heavy", element: "frost" },
      "frost wave": { chance: 18, damage: [18, 28], parryable: false, element: "frost" },
    },
    chance: 8,
    drops: {
      "frost crystal": { chance: 100, min_drop: 1, max_drop: 3 },
      stone: { chance: 100, min_drop: 5, max_drop: 10 },
      "giant hide": { chance: 50, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 10,
    dodge_chance: 0,
    parry_rate: 45,
    dodge_rate: 0,
  },
  "goblin king": {
    icon: "👑",
    hp: 320,
    block_chance: 25,
    block_reduction: 0.55,
    basic_attack: { damage: [18, 28] },
    abilities: {
      "royal slash": { chance: 25, damage: [22, 34] },
      "goblin barrage": { chance: 18, damage: [10, 16], hits: 2, type: "fast" },
    },
    chance: 0,
    drops: {
      "goblin blade": { chance: 100, min_drop: 1, max_drop: 1 },
      gold: { chance: 100, min_drop: 2, max_drop: 5 },
      iron: { chance: 100, min_drop: 3, max_drop: 7 },
    },
    parry_chance: 20,
    dodge_chance: 15,
    parry_rate: 55,
    dodge_rate: 55,
  },
  "alpha wolf": {
    icon: "🐺",
    hp: 300,
    block_chance: 5,
    block_reduction: 0.45,
    basic_attack: { damage: [20, 30] },
    abilities: {
      "alpha pounce": { chance: 25, damage: [24, 36], type: "heavy" },
      "double bite": { chance: 20, damage: [11, 17], hits: 2, type: "fast" },
    },
    chance: 0,
    drops: {
      fang: { chance: 100, min_drop: 3, max_drop: 6 },
      "dire fang": { chance: 100, min_drop: 1, max_drop: 2 },
      leather: { chance: 100, min_drop: 4, max_drop: 8 },
    },
    parry_chance: 5,
    dodge_chance: 30,
    parry_rate: 35,
    dodge_rate: 75,
  },
  "orc warlord": {
    icon: "👹",
    hp: 500,
    block_chance: 30,
    block_reduction: 0.6,
    basic_attack: { damage: [28, 42] },
    abilities: {
      "warlord smash": { chance: 25, stun: 40, stun_turns: 3, damage: [38, 55], type: "heavy" },
      "battle roar": { chance: 15, stun: 25, stun_turns: 2, heal: [20, 35] },
    },
    chance: 0,
    drops: {
      steel: { chance: 100, min_drop: 5, max_drop: 10 },
      "orc tusk": { chance: 100, min_drop: 1, max_drop: 3 },
      gold: { chance: 100, min_drop: 3, max_drop: 8 },
    },
    parry_chance: 18,
    dodge_chance: 4,
    parry_rate: 55,
    dodge_rate: 30,
  },
  "ancient golem": {
    icon: "🗿",
    hp: 650,
    block_chance: 40,
    block_reduction: 0.7,
    basic_attack: { damage: [32, 48] },
    abilities: {
      "ancient fist": { chance: 25, stun: 40, stun_turns: 3, damage: [45, 65], type: "heavy" },
      "crystal burst": { chance: 18, damage: [25, 40], parryable: false },
    },
    chance: 0,
    drops: {
      "ancient crystal": { chance: 100, min_drop: 2, max_drop: 5 },
      "ancient heart": { chance: 100, min_drop: 1, max_drop: 1 },
      stone: { chance: 100, min_drop: 10, max_drop: 20 },
    },
    parry_chance: 18,
    dodge_chance: 0,
    parry_rate: 55,
    dodge_rate: 0,
  },
  "frost giant king": {
    icon: "👑",
    hp: 800,
    block_chance: 35,
    block_reduction: 0.65,
    basic_attack: { damage: [38, 55] },
    abilities: {
      "king's hammer": { chance: 25, stun: 40, stun_turns: 3, damage: [50, 72], type: "heavy", element: "frost" },
      blizzard: { chance: 18, damage: [30, 45], parryable: false, warning: true, element: "frost" },
      "frost guard": { chance: 12, heal: [25, 45] },
    },
    chance: 0,
    drops: {
      "frost crystal": { chance: 100, min_drop: 3, max_drop: 6 },
      "ancient crystal": { chance: 50, min_drop: 1, max_drop: 2 },
      "frost king core": { chance: 100, min_drop: 1, max_drop: 1 },
    },
    parry_chance: 15,
    dodge_chance: 0,
    parry_rate: 50,
    dodge_rate: 0,
  },
  "ash demon": {
    icon: "👿",
    hp: 900,
    block_chance: 25,
    block_reduction: 0.6,
    basic_attack: { damage: [42, 60] },
    abilities: {
      inferno: { chance: 25, stun: 30, stun_turns: 2, damage: [50, 75], parryable: false, warning: true, element: "fire" },
      "demon drain": { chance: 18, damage: [25, 40], heal: [20, 35] },
      "void curse": {
        chance: 15,
        damage: [20, 30],
        special_effect: { type: "poison", chance: 90, damage: 7, turns: 4 },
      },
    },
    chance: 0,
    drops: {
      "demon core": { chance: 100, min_drop: 1, max_drop: 2 },
      "demon horn": { chance: 100, min_drop: 3, max_drop: 6 },
      "void crystal": { chance: 50, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 15,
    dodge_chance: 15,
    parry_rate: 55,
    dodge_rate: 50,
  },
  "the unnamed king": {
    icon: "👑",
    hp: 500,
    block_chance: 30,
    block_reduction: 0.65,
    basic_attack: { damage: [32, 45] },
    abilities: {
      "forgotten decree": {
        chance: 20,
        damage: [32, 49],
        type: "heavy",
        warning: true,
        telegraph: "speaks a command the world obeys",
      },
      "erase name": {
        chance: 12,
        damage: [21, 35],
        parryable: false,
        blockable: false,
        dodgeable: true,
      },
      godfall: {
        chance: 8, stun: 40, stun_turns: 3,
        damage: [45, 66],
        type: "slow",
        parryable: false,
        blockable: false,
        warning: true,
        telegraph: "raises a hand toward the sky",
      },
    },
    chance: 0,
    drops: {
      "ancient heart": { chance: 100, min_drop: 1, max_drop: 1 },
      "ancient crystal": { chance: 100, min_drop: 4, max_drop: 8 },
      "void crystal": { chance: 40, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 20,
    dodge_chance: 12,
    parry_rate: 60,
    dodge_rate: 45,
  },
  "the leftover": {
    icon: "◼",
    hp: 750,
    block_chance: 5,
    block_reduction: 0.25,
    basic_attack: { damage: [38, 56] },
    abilities: {
      "missing texture": { chance: 20, damage: [31, 52], parryable: false, blockable: false },
      "invalid state": { chance: 18, damage: [24, 42], type: "fast", dodgeable: false },
      rollback: { chance: 10, heal: [40, 70] },
      "out of bounds": {
        chance: 8, stun: 35, stun_turns: 3,
        damage: [52, 77],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "moves beyond the edge of the encounter",
      },
    },
    chance: 0,
    drops: {
      "void crystal": { chance: 100, min_drop: 3, max_drop: 7 },
      "ancient crystal": { chance: 60, min_drop: 2, max_drop: 4 },
    },
    parry_chance: 5,
    dodge_chance: 20,
    parry_rate: 25,
    dodge_rate: 65,
  },
  "the watcher": {
    icon: "👁️",
    hp: 1000,
    block_chance: 15,
    block_reduction: 0.5,
    basic_attack: { damage: [42, 63] },
    abilities: {
      observe: { chance: 18, damage: [14, 21] },
      prediction: { chance: 20, damage: [31, 49], type: "fast", dodgeable: false },
      counterfactual: { chance: 12, damage: [49, 70], parryable: false, blockable: false },
      "look away": { chance: 8, heal: [50, 90] },
    },
    chance: 0,
    drops: {
      "void crystal": { chance: 100, min_drop: 5, max_drop: 10 },
      "ancient heart": { chance: 50, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 25,
    dodge_chance: 25,
    parry_rate: 70,
    dodge_rate: 70,
  },
  "the witness": {
    icon: "◉",
    hp: 1400,
    block_chance: 0,
    block_reduction: 0.0,
    basic_attack: { damage: [49, 70] },
    abilities: {
      remember: { chance: 16, damage: [38, 59], parryable: false },
      forget: { chance: 14, damage: [42, 66], blockable: false, dodgeable: true },
      reload: { chance: 8, heal: [75, 125] },
      "fourth wall": {
        chance: 7, stun: 40, stun_turns: 3,
        damage: [56, 84],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "stops attacking the hero and addresses the observer",
      },
    },
    chance: 0,
    drops: {
      "void crystal": { chance: 100, min_drop: 10, max_drop: 20 },
      "ancient heart": { chance: 100, min_drop: 2, max_drop: 4 },
    },
    parry_chance: 35,
    dodge_chance: 35,
    parry_rate: 75,
    dodge_rate: 75,
  },
};

// ---------- Chapter 6-10 story bosses ----------
Object.assign(monsters, {
  "the archivist": {
    icon: "📚",
    hp: 1700,
    block_chance: 20,
    block_reduction: 0.55,
    basic_attack: { damage: [54, 76] },
    abilities: {
      "cross reference": { chance: 20, damage: [40, 62], type: "fast", dodgeable: false },
      "overdue notice": { chance: 16, damage: [48, 72], parryable: false },
      "restore backup": { chance: 10, heal: [60, 110] },
      "sealed vault": {
        chance: 8, stun: 40, stun_turns: 3,
        damage: [62, 90],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "slams shut every shelf with",
      },
    },
    chance: 0,
    drops: {
      "void crystal": { chance: 100, min_drop: 6, max_drop: 12 },
      "ancient heart": { chance: 60, min_drop: 1, max_drop: 2 },
      "soul shard": { chance: 100, min_drop: 2, max_drop: 4 },
    },
    parry_chance: 25,
    dodge_chance: 20,
    parry_rate: 65,
    dodge_rate: 60,
  },
  "the first hero": {
    icon: "🗡️",
    hp: 2000,
    block_chance: 25,
    block_reduction: 0.6,
    basic_attack: { damage: [60, 84], type: "fast" },
    abilities: {
      "familiar strike": { chance: 22, damage: [52, 78], type: "fast", parryable: false },
      "worn out sword": {
        chance: 18,
        damage: [70, 96],
        type: "heavy",
        warning: true,
        telegraph: "raises a blade you recognise to deliver",
      },
      "give up": { chance: 8, heal: [80, 140] },
      "last attempt": {
        chance: 8, stun: 35, stun_turns: 2,
        damage: [74, 104],
        type: "slow",
        parryable: false,
        blockable: false,
        warning: true,
        telegraph: "stops, then says your name before",
      },
    },
    chance: 0,
    drops: {
      "void crystal": { chance: 100, min_drop: 7, max_drop: 14 },
      "ancient heart": { chance: 70, min_drop: 1, max_drop: 2 },
      "ancient crystal": { chance: 100, min_drop: 4, max_drop: 8 },
    },
    parry_chance: 35,
    dodge_chance: 25,
    parry_rate: 75,
    dodge_rate: 60,
  },
  "the editor": {
    icon: "✒️",
    hp: 2400,
    block_chance: 10,
    block_reduction: 0.4,
    basic_attack: { damage: [66, 92] },
    abilities: {
      strikethrough: { chance: 22, damage: [56, 84], parryable: false, dodgeable: true },
      redact: { chance: 18, damage: [50, 78], blockable: false },
      revise: { chance: 10, heal: [90, 150] },
      "delete scene": {
        chance: 8, stun: 35, stun_turns: 3,
        damage: [86, 120],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "marks the whole encounter for",
      },
    },
    chance: 0,
    drops: {
      "void crystal": { chance: 100, min_drop: 8, max_drop: 16 },
      "ancient heart": { chance: 70, min_drop: 1, max_drop: 3 },
      "demon core": { chance: 100, min_drop: 1, max_drop: 2 },
    },
    parry_chance: 30,
    dodge_chance: 30,
    parry_rate: 70,
    dodge_rate: 70,
  },
  "the author": {
    icon: "📖",
    hp: 2800,
    block_chance: 15,
    block_reduction: 0.5,
    basic_attack: { damage: [72, 100] },
    abilities: {
      "plot twist": { chance: 22, damage: [60, 90], type: "fast", dodgeable: false },
      "writer's block": {
        chance: 14,
        damage: [40, 64],
        special_effect: { type: "poison", chance: 90, damage: 9, turns: 4 },
      },
      "second draft": { chance: 10, heal: [100, 170] },
      "deus ex machina": {
        chance: 8, stun: 40, stun_turns: 3,
        damage: [94, 130],
        type: "heavy",
        parryable: false,
        blockable: false,
        warning: true,
        telegraph: "writes in a sudden rescue and releases",
      },
    },
    chance: 0,
    drops: {
      "void crystal": { chance: 100, min_drop: 10, max_drop: 18 },
      "ancient heart": { chance: 80, min_drop: 2, max_drop: 3 },
      "ancient crystal": { chance: 100, min_drop: 6, max_drop: 10 },
    },
    parry_chance: 35,
    dodge_chance: 35,
    parry_rate: 75,
    dodge_rate: 75,
  },
  "clockwork hound": {
    icon: "🐺", hp: 96, block_chance: 10, block_reduction: 0.25,
    basic_attack: { damage: [12, 18] },
    abilities: {
      "gear bite": { chance: 18, damage: [16, 22], special_effect: { type: "bleed", chance: 35, damage: 3, turns: 2 } },
      "steam vent": { chance: 12, damage: [10, 16], element: "fire", special_effect: { type: "weakened", chance: 35, damage: 0, turns: 2 } },
    },
    chance: 0, drops: { iron: { chance: 80, min_drop: 2, max_drop: 4 }, coal: { chance: 60, min_drop: 1, max_drop: 3 } },
    parry_chance: 18, dodge_chance: 12, parry_rate: 65, dodge_rate: 55,
  },
  "mire witch": {
    icon: "🧙", hp: 158, block_chance: 6, block_reduction: 0.2,
    basic_attack: { damage: [18, 25] }, resist: { fire: 0, frost: 35 },
    abilities: {
      "bog hex": { chance: 18, damage: [12, 18], special_effect: { type: "poison", chance: 70, damage: 5, turns: 3 } },
      "sapping mist": { chance: 14, damage: [10, 16], element: "frost", special_effect: { type: "slow", chance: 55, damage: 0, turns: 2 } },
    },
    chance: 0, drops: { fang: { chance: 70, min_drop: 1, max_drop: 3 }, "frost crystal": { chance: 20, min_drop: 1, max_drop: 1 } },
    parry_chance: 12, dodge_chance: 12, parry_rate: 60, dodge_rate: 60,
  },
  "archive stalker": {
    icon: "📚", hp: 420, block_chance: 14, block_reduction: 0.3,
    basic_attack: { damage: [38, 50] }, resist: { fire: 20, frost: 20 },
    abilities: {
      "redacted strike": { chance: 18, damage: [44, 58], blockable: false },
      "memory leak": { chance: 14, damage: [32, 42], special_effect: { type: "weakened", chance: 70, damage: 0, turns: 2 } },
    },
    chance: 0, drops: { "void crystal": { chance: 30, min_drop: 1, max_drop: 2 }, "soul shard": { chance: 50, min_drop: 1, max_drop: 3 } },
    parry_chance: 28, dodge_chance: 18, parry_rate: 70, dodge_rate: 65,
  },
  "margin warden": {
    icon: "✒️", hp: 860, block_chance: 18, block_reduction: 0.35,
    basic_attack: { damage: [56, 72] }, resist: { fire: 25, frost: 25 },
    abilities: {
      "erase line": { chance: 16, damage: [62, 80], dodgeable: false, special_effect: { type: "slow", chance: 60, damage: 0, turns: 2 } },
      "correct the record": { chance: 12, heal: [70, 105] },
    },
    chance: 0, drops: { "ancient crystal": { chance: 35, min_drop: 1, max_drop: 2 }, "void crystal": { chance: 40, min_drop: 1, max_drop: 3 } },
    parry_chance: 32, dodge_chance: 20, parry_rate: 72, dodge_rate: 68,
  },
  "the last save": {
    icon: "💾",
    hp: 3200,
    block_chance: 5,
    block_reduction: 0.3,
    basic_attack: { damage: [80, 112] },
    abilities: {
      autosave: { chance: 16, damage: [64, 96], parryable: false },
      corrupt: {
        chance: 14,
        damage: [70, 100],
        blockable: false,
        dodgeable: true,
        special_effect: { type: "poison", chance: 80, damage: 10, turns: 4 },
      },
      "load previous": { chance: 10, heal: [120, 200] },
      overwrite: {
        chance: 8, stun: 40, stun_turns: 3,
        damage: [100, 140],
        type: "slow",
        parryable: false,
        blockable: false,
        dodgeable: false,
        warning: true,
        telegraph: "prepares to overwrite everything with",
      },
    },
    chance: 0,
    drops: {
      "void crystal": { chance: 100, min_drop: 15, max_drop: 25 },
      "ancient heart": { chance: 100, min_drop: 3, max_drop: 5 },
    },
    parry_chance: 40,
    dodge_chance: 40,
    parry_rate: 75,
    dodge_rate: 75,
  },
});
